config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/register' => 'devise/registrations#new'
  end

  get 'pages/index'  

  scope "/:locale" do

    namespace :admin, path: '/master' do
      get "/" => "dashboards#index", as: 'master'
      resources :dashboards, only: [:index]
      resources :users do
        resources :videos, only: [:index, :edit, :update, :destroy]
        resources :pictures, only: [:index, :edit, :update, :destroy]
      end
    end

    resource :account, only: [:show, :edit, :update]
    resources :pictures do
      collection do
        get 'next_stories'
      end
    end
    resources :videos do
      collection do
        get 'next_stories'
      end
    end
    
  end

  get '/v=:id' => 'videos#show', as: 'watch' #example - awesomepv.dev/v=aNFo5HWC3QI
  get '/p=:id' => 'pictures#show', as: 'view'

  root 'pages#index'
  
end

app/models/video.rb
class Video < ActiveRecord::Base
  acts_as_paranoid

  extend FriendlyId #https://github.com/norman/friendly_id

  friendly_id :vid, use: [:slugged, :finders, :history]

  belongs_to :user, foreign_key: :user_id

  validates :title, length: { maximum: 240 }, presence: true
  validates :description, length: { maximum: 500 }, allow_blank: true
  validates :youtube_id, presence: true, uniqueness: true

  self.per_page = 12

  default_scope -> { order('videos.created_at DESC') }
  scope :published, -> { where('state = ?', 'published').unscope(:order).order('`videos`.published_at DESC') }
  scope :featured, -> { where(featured: true) }
  scope :published_only, -> { where('featured IS NOT TRUE') }
  scope :random, -> { unscope(:order).order('RAND()') }

  after_create :send_video_email

  protected

  def published?
    state == 'published'
  end

  def send_video_email
    VideoMailer.video_email(self.user).deliver
 end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  before_filter :set_user, only: [:index, :edit, :update, :destroy]
  before_filter :set_video, only: [:edit, :update, :destroy]
  before_filter :store_location, only: [:index]
  before_filter :require_admin

  def index
    @videos = Video.where(user_id: @user)
    respond_to do |format|
      format.html { @videos }
      format.json { render json: @videos.to_json }
    end
  end

  def edit
    if @video
      render
    else
      redirect_to admin_user_videos_path, notice: "Video not found."
    end
  end

  def update
    if @video.update(video_params)
      redirect_to admin_user_videos_path, notice: "Video #{@video.vid} has been updated."
    else
      render 'edit'
    end
  end

  def destroy
    @video.destroy
    redirect_to admin_user_videos_path, notice: "Video has been deleted."
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_video
    @video = Video.where(slug: params[:id], user: @user).take
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :set_user, only: [:index, :new, :create, :edit, :update, :destroy]
  before_filter :set_video, only: [:edit, :update, :destroy]
  before_filter :require_user, only: [:index, :new, :create, :edit, :update, :destroy]
  before_filter :store_location, only: [:index]

  def index
    @videos = Video.where(user_id: @user)
    respond_to do |format|
      format.html { @videos }
      format.json { render json: @videos.to_json }
    end
  end

  def new
    @video ||= Video.new
    render
  end

  def create
    @video = @user.videos.new(video_params)
    if @video.save
      @video.update_attributes(:state => "published")
      @video.update_attributes(:published_at => Time.zone.now)

      random = [('a'..'z'), ('A'..'Z'), ('1'..'9')].map { |i| i.to_a }.flatten
      vid = (0...12).map { random[rand(random.length)] }.join
      @video.update_attributes(:vid => vid)

      redirect_to watch_path(@video), notice: "New video has been created."
    else
      render 'new'
    end
  end

  def show
    @video = Video.find(params[:id])
    respond_to do |format|
      format.html { @video }
      format.json { render json: @video.to_json }
    end

    @videos = Video.all.limit(4)
    @random = @videos.random
    @video.increment!(:views)
  end

  def edit
    if @video
      render
    else
      redirect_to video_path, notice: "Video not found."
    end
  end

  def update
    if @video.update(video_params)
      redirect_to video_path, notice: "#{@video.title} has been updated."
    else
      render 'edit'
    end
  end

  def destroy
    @video.destroy
    redirect_to videos_path, notice: "Video has been deleted."
  end

  private

  def set_user
    @user = current_user
  end

  def set_video
    @video = Video.where(slug: params[:id], user: @user).take
  end
end

app/helpers/admin/videos_helper.rb
module Admin::VideosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_sidebar.html.erb
<div class="list-group">
  <%= link_to t(:acc_sett), edit_user_registration_path, :class => 'list-group-item' %>
  <%= link_to t(:profile_details), account_path, :class => 'list-group-item' %>
  <%= link_to t(:video_details), videos_path, :class => 'list-group-item active' %>
  <%= link_to t(:picture_details), pictures_path, :class => 'list-group-item' %>
</div>

app/views/videos/edit.html.erb
<div class="page-header">
  <h1><%= t(:edit_video) %> <small><%= t(:edit_video_desc) %></small></h1>
</div>

<div class="row">
  <div class="col-md-4">
    <%= render partial: "sidebar" %>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t(:video_details) %></h3>
      </div>
      <%= form_for :video, url: video_path(@video), method: :patch do |f| %>
      <div class="panel-body">

        <% if @video.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><%= pluralize(@video.errors.count, "error") %> prohibited
            this video from being saved:</strong>
            <ul>
              <% @video.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
        <% end %>
        
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :title, t(:video_title) %>
              <%= f.text_field :title, :class => "form-control" %>
              <p class="small help-block"><%= t(:video_title_limit) %></p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :description, t(:video_description) %>
              <%= f.text_area :description, :class => "form-control", :rows => 4 %>
              <p class="small help-block"><%= t(:video_desc_limit) %></p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :youtube_id, t(:youtube_id) %>
              <%= f.text_field :youtube_id, :class => "form-control" %>
              <p class="small help-block"><%= t(:youtube_instruc) %></p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :source, t(:source) %>
              <%= f.select(:source, options_for_select([['Youtube', 'Youtube'], ['Vimeo', 'Vimeo']], @video.source), {}, {:class => "form-control"}) %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="checkbox">
              <label>
              <%= f.check_box :featured, :type => 'checkbox' %> <%= t(:as_featured) %>
              </label>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <div class="form-group">
          <%= f.button t(:edit_video), :class => "btn btn-primary", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Updating ..." } %>
          <%= link_to t(:cancel), videos_path, :class => "btn btn-link" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<div class="page-header">
  <h1><%= t(:video_list) %> <small><%= t(:manage_video) %></small></h1>
</div>

<div class="row">
  <div class="col-md-4">
    <%= render partial: "sidebar" %>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t(:list_video) %> <%= link_to t(:new_video), new_video_path, :class => "pull-right btn btn-primary btn-xs", :style => "color:#ffffff;" %></h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover" id="videoDetails">
            <thead>
              <tr>
                <th><%= t(:video_title) %></th>
                <th><%= t(:video_date) %></th>
                <th class="col-md-2"><%= t(:action) %></th>
              </tr>
            </thead>
            <tbody>
              <% @videos.each do |video| %>
              <tr>
                <td><%= video.try(:title) %></td>
                <td><%= video.try(:created_at).strftime("%d %B %Y") %></td>
                <td>
                  <div class="btn-group btn-group-xs btn-group-justified">
                  <%= link_to watch_path(video), :class => "btn btn-default", "data-toggle" => "tooltip", :title => "Show the video" do %>
                    <span class="glyphicon glyphicon-eye-open"></span>
                  <% end %>
                  <%= link_to edit_video_path(video), :class => "btn btn-info", "data-toggle" => "tooltip", :title => "Edit this video" do %>
                    <span class="glyphicon glyphicon-edit"></span>
                  <% end %>
                  <%= link_to video_path(video), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", "data-toggle" => "tooltip", :title => "Remove this video" do %>
                    <span class="glyphicon glyphicon-remove"></span>
                  <% end %>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready( function () {
    $('#videoDetails').DataTable();
} );
</script>

app/views/videos/new.html.erb
<div class="page-header">
  <h1><%= t(:new_video) %> <small><%= t(:new_video_desc) %></small></h1>
</div>

<div class="row">
  <div class="col-md-4">
    <%= render partial: "sidebar" %>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t(:video_details) %></h3>
      </div>
      <%= form_for :video, url: videos_path, method: :post do |f| %>
      <div class="panel-body">

        <% if @video.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><%= pluralize(@video.errors.count, "error") %> prohibited
            this video from being saved:</strong>
            <ul>
              <% @video.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
        <% end %>

        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :title, t(:video_title) %>
              <%= f.text_field :title, :class => "form-control" %>
              <p class="small help-block"><%= t(:video_title_limit) %></p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :description, t(:video_description) %>
              <%= f.text_area :description, :class => "form-control", :rows => 4 %>
              <p class="small help-block"><%= t(:video_desc_limit) %></p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :youtube_id, t(:youtube_id) %>
              <%= f.text_field :youtube_id, :class => "form-control" %>
              <p class="small help-block">
                <a href="" class="btn-primary" data-toggle="modal" data-target="#instruction"><%= t(:youtube_instruc) %></a>
              </p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :source, t(:source) %>
              <%= f.select(:source, options_for_select([['Youtube', 'Youtube'], ['Vimeo', 'Vimeo']], 'Youtube'), {}, {:class => "form-control"}) %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="checkbox">
              <label>
              <%= f.check_box :featured, :type => 'checkbox' %> <%= t(:as_featured) %>
              </label>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <div class="form-group">
          <%= f.button t(:submit_video), :class => "btn btn-primary", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Submitting ..." } %>
          <%= link_to t(:cancel), videos_path, :class => "btn btn-link" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="instruction" tabindex="-1" role="dialog" aria-labelledby="instruction" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Instruction</h4>
      </div>
      <div class="modal-body">
        <p><%= image_tag('vid-instruction.png', :alt => "Youtube ID Instruction", :class => 'img-responsive') %></p>
        <p>So what you need is to copy the youtube id <strong>AFTER</strong> v=</p>
        <p class="lead">For example:</p>
        <p>Youtube URL is <strong>http://www.youtube.com/watch?v=7n4kXwjDquI</strong> so what you need is the youtube id which is <strong>7n4kXwjDquI</strong></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">I Understand</button>
      </div>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<% content_for :title do %>
  <%= "#{@video.try(:title)}" %> - Awesome Picture & Video
<% end %>
<% content_for :meta_tags do %>
  <%= render :partial => 'application/meta_tags',
             :locals => {
                  :type => "website",
                  :title => "#{@video.try(:title)}",
                  :url => request.url,
                  :description => "#{@video.try(:description)}",
                  :canonical => request.url,
                  :og_title => "#{@video.try(:title)}",
                  :og_description => "#{@video.try(:description)}",
                  :og_image => "http://i3.ytimg.com/vi/#{@video.try(:youtube_id)}/maxresdefault.jpg"
             } %>
<% end %>

<!-- Latest Videos -->
<div id="latestVideos">
<!-- Video 1 -->
<h3><%= @video.title %></h3>
<div class="metaDetails">
  <p><%= @video.views %> <%= t(:people_viewed) %></p>
  <span><%= t(:source) %></span><span2><%= @video.source %></span2>
</div>
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" width="930" height="523" src="//www.youtube.com/embed/<%= @video.youtube_id %>?rel=0&showinfo=0&iv_load_policy=3&autoplay=1&vq=hd720" frameborder="0" allowfullscreen></iframe>
</div>

<div class="btn-group btn-group-lg btn-group-justified">
  <a href="javascript:void(0)" onclick="PopupCenter('//www.facebook.com/sharer/sharer.php?u=<%= request.url %>', 'myPop1',600,450);" class="btn btn-facebook"><%= t(:share_fb) %></a>
  <a href="javascript:void(0)" onclick="PopupCenter('//twitter.com/intent/tweet?source=tweetbutton&original_referer=<%= request.url %>&text=<%= @video.try(:title) %>&url=<%= request.url %>', 'myPop1',600,450);" class="btn btn-twitter"><%= t(:share_twitter) %></a>
</div>



<div class="metaDetails">
  <p class="small"><%= t(:published_on) %> <%= @video.published_at.strftime("%d %B %Y") %> <%= t(:by) %> <%= @video.user.username.upcase %></p>
</div>
<p class="text-justify"><%=h @video.description %></p>

</div>
<!-- Latest Videos End -->

<!-- Random Videos -->
<div id="featuredVideos">
  <div class="separator m-b-xl">
    <span><%= t(:may_like) %></span>
  </div>

  <div class="row">
    <% @random.each do |video| %>
    <div class="col-md-3 col-sm-6 col-xs-6">
      <%= link_to watch_path(video) do %>
      <img src="//i3.ytimg.com/vi/<%= video.youtube_id %>/maxresdefault.jpg" alt="" class="img-responsive">
      <% end %>
      <h4><%= video.title %></h4>
      <p class="small"><%= t(:published_on) %> <%= video.published_at.strftime("%d %B %Y") %></p>
    </div>
    <% end %>
  </div>
</div>
<!-- Random Videos End -->

<script type="text/javascript">
$(document).ready(function(){
  mixpanel.track("Video played", {
    "Video ID": '<%= @video.vid %>'
  });
});
</script>