config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/register' => 'devise/registrations#new'
  end

  get 'pages/index'  

  scope "/:locale" do

    namespace :admin, path: '/master' do
      get "/" => "dashboards#index", as: 'master'
      resources :dashboards, only: [:index]
      resources :users do
        resources :videos, only: [:index, :edit, :update, :destroy]
        resources :pictures, only: [:index, :edit, :update, :destroy]
      end
    end

    resource :account, only: [:show, :edit, :update]
    resources :pictures do
      collection do
        get 'next_stories'
      end
    end
    resources :videos do
      collection do
        get 'next_stories'
      end
    end
    
  end

  get '/v=:id' => 'videos#show', as: 'watch' #example - awesomepv.dev/v=aNFo5HWC3QI
  get '/p=:id' => 'pictures#show', as: 'view'

  root 'pages#index'
  
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :cover_photo, CoverPhotoUploader
  
  acts_as_paranoid

  extend FriendlyId #https://github.com/norman/friendly_id

  friendly_id :pid, use: [:slugged, :finders, :history]

  belongs_to :user, foreign_key: :user_id

  validates :title, length: { maximum: 240 }, presence: true
  validates_presence_of   :cover_photo

  # self.per_page = 4

  default_scope -> { order('pictures.created_at DESC') }
  scope :published, -> { where('state = ?', 'published').unscope(:order).order('`pictures`.published_at DESC') }
  scope :featured, -> { where(featured: true) }
  scope :published_only, -> { where('featured IS NOT TRUE') }
  scope :random, -> { unscope(:order).order('RAND()') }

  protected

  def published?
    state == 'published'
  end
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < ApplicationController
  before_filter :set_user, only: [:index, :edit, :update, :destroy]
  before_filter :set_picture, only: [:edit, :update, :destroy]
  before_filter :store_location, only: [:index]
  before_filter :require_admin

  def index
    @pictures = Picture.where(user_id: @user)
    respond_to do |format|
      format.html { @pictures }
      format.json { render json: @pictures.to_json }
    end
  end

  def edit
    if @picture
      render
    else
      redirect_to admin_user_pictures_path, notice: "Picture not found."
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to admin_user_pictures_path, notice: "Picture #{@picture.pid} has been updated."
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to admin_user_pictures_path, notice: "Picture has been deleted."
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_picture
    @picture = Picture.where(slug: params[:id], user: @user).take
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :set_user, only: [:index, :new, :create, :edit, :update, :destroy]
  before_filter :set_picture, only: [:edit, :update, :destroy]
  before_filter :require_user, only: [:index, :new, :create, :edit, :update, :destroy]
  before_filter :store_location, only: [:index]

  def index
    @pictures = Picture.where(user_id: @user)
    respond_to do |format|
      format.html { @pictures }
      format.json { render json: @pictures.to_json }
    end
  end

  def new
    @picture ||= Picture.new
    render
  end

  def create
    @picture = @user.pictures.new(picture_params)
    if @picture.save
      @picture.update_attributes(:state => "published")
      @picture.update_attributes(:published_at => Time.zone.now)

      random = [('a'..'z'), ('A'..'Z'), ('1'..'9')].map { |i| i.to_a }.flatten
      pid = (0...12).map { random[rand(random.length)] }.join
      @picture.update_attributes(:pid => pid)

      redirect_to view_path(@picture), notice: "New picture has been created."
    else
      render 'new'
    end
  end

  def show
    # url = "http://rubygems.org/api/v1/versions/httparty.json"
    # @response = HTTParty.get(url)
    # @result = JSON.parse(@response.body)

    @picture = Picture.find(params[:id])
    respond_to do |format|
      format.html { @picture }
      format.json { render json: @picture.to_json }
    end

    @pictures = Picture.all
    @random = @pictures.random
    @picture.increment!(:views)
  end

  def edit
    if @picture
      render
    else
      redirect_to picture_path, notice: "Picture not found."
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to picture_path, notice: "#{@picture.title} has been updated."
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "Picture has been deleted."
  end

  private

  def set_user
    @user = current_user
  end

  def set_picture
    @picture = Picture.where(slug: params[:id], user: @user).take
  end
end

app/helpers/admin/pictures_helper.rb
module Admin::PicturesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_sidebar.html.erb
<div class="list-group">
  <%= link_to t(:acc_sett), edit_user_registration_path, :class => 'list-group-item' %>
  <%= link_to t(:profile_details), account_path, :class => 'list-group-item' %>
  <%= link_to t(:video_details), videos_path, :class => 'list-group-item' %>
  <%= link_to t(:picture_details), pictures_path, :class => 'list-group-item active' %>
</div>

app/views/pictures/edit.html.erb
<div class="page-header">
  <h1><%= t(:edit_picture) %> <small><%= t(:edit_picture_desc) %></small></h1>
</div>

<div class="row">
  <div class="col-md-4">
    <%= render partial: "sidebar" %>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t(:picture_details) %></h3>
      </div>
      <%= form_for :picture, url: picture_path(@picture), method: :patch do |f| %>
      <div class="panel-body">

        <% if @picture.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><%= pluralize(@picture.errors.count, "error") %> prohibited
            this picture from being saved:</strong>
            <ul>
              <% @picture.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
        <% end %>
        
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :title, t(:picture_title) %>
              <%= f.text_field :title, :class => "form-control" %>
              <p class="small help-block"><%= t(:picture_title_limit) %></p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :content, t(:picture_desc) %>
              <%= f.text_area :content, :class => "form-control", :rows => 4 %>
              <p class="small help-block"><%= t(:picture_desc_limit) %></p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :cover_photo, t(:current_photo) %><br />
              <% if @picture.cover_photo.url.present? %>
                <%= image_tag(@picture.cover_photo.url(:thumb))  %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
                <%= f.label :cover_photo, t(:replace_photo) %>
                <%= f.file_field :cover_photo %>
                <%= f.hidden_field :cover_photo_cache %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="checkbox">
              <label>
              <%= f.check_box :featured, :type => 'checkbox' %> <%= t(:as_featured_pic) %>
              </label>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <div class="form-group">
          <%= f.button t(:edit_picture), :class => "btn btn-primary", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Updating ..." } %>
          <%= link_to t(:cancel), pictures_path, :class => "btn btn-link" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="page-header">
  <h1><%= t(:picture_list) %> <small><%= t(:manage_picture) %></small></h1>
</div>

<div class="row">
  <div class="col-md-4">
    <%= render partial: "sidebar" %>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t(:list_picture) %> <%= link_to t(:new_picture), new_picture_path, :class => "pull-right btn btn-primary btn-xs", :style => "color:#ffffff;" %></h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover" id="pictureDetails">
            <thead>
              <tr>
                <th><%= t(:picture_title) %></th>
                <th><%= t(:picture_date) %></th>
                <th class="col-md-2"><%= t(:action) %></th>
              </tr>
            </thead>
            <tbody>
              <% @pictures.each do |picture| %>
              <tr>
                <td><%= picture.try(:title) %></td>
                <td><%= picture.try(:created_at).strftime("%d %B %Y") %></td>
                <td>
                  <div class="btn-group btn-group-xs btn-group-justified">
                  <%= link_to view_path(picture), :class => "btn btn-default", "data-toggle" => "tooltip", :title => "Show the picture" do %>
                    <span class="glyphicon glyphicon-eye-open"></span>
                  <% end %>
                  <%= link_to edit_picture_path(picture), :class => "btn btn-info", "data-toggle" => "tooltip", :title => "Edit this picture" do %>
                    <span class="glyphicon glyphicon-edit"></span>
                  <% end %>
                  <%= link_to picture_path(picture), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", "data-toggle" => "tooltip", :title => "Remove this picture" do %>
                    <span class="glyphicon glyphicon-remove"></span>
                  <% end %>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready( function () {
    $('#pictureDetails').DataTable();
} );
</script>

app/views/pictures/new.html.erb
<div class="page-header">
  <h1><%= t(:new_picture) %> <small><%= t(:new_picture_desc) %></small></h1>
</div>

<div class="row">
  <div class="col-md-4">
    <%= render partial: "sidebar" %>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t(:picture_details) %></h3>
      </div>
      <%= form_for :picture, url: pictures_path, :html => {:multipart => true}, method: :post do |f| %>
      <div class="panel-body">

        <% if @picture.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><%= pluralize(@picture.errors.count, "error") %> prohibited
            this picture from being saved:</strong>
            <ul>
              <% @picture.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
        <% end %>

        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :title, t(:picture_title) %>
              <%= f.text_field :title, :class => "form-control" %>
              <p class="small help-block"><%= t(:picture_title_limit) %></p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :content, t(:picture_desc) %>
              <%= f.text_area :content, :class => "form-control", :rows => 4 %>
              <p class="small help-block"><%= t(:picture_desc_limit) %></p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :cover_photo, t(:set_cover_photo) %>
              <%= f.file_field :cover_photo %>
              <%= f.hidden_field :cover_photo_cache %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="checkbox">
              <label>
              <%= f.check_box :featured, :type => 'checkbox' %> <%= t(:as_featured_pic) %>
              </label>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <div class="form-group">
          <%= f.button t(:submit_picture), :class => "btn btn-primary", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Submitting ..." } %>
          <%= link_to t(:batal), pictures_path, :class => "btn btn-link" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/show.html.erb
<% content_for :title do %>
  <%= "#{@picture.try(:title)}" %> - Awesome Picture & Video
<% end %>
<% content_for :meta_tags do %>
  <%= render :partial => 'application/meta_tags',
             :locals => {
                  :type => "website",
                  :title => "#{@picture.try(:title)}",
                  :url => request.url,
                  :description => "#{@picture.try(:content)}",
                  :canonical => request.url,
                  :og_title => "#{@picture.try(:title)}",
                  :og_description => "#{@picture.try(:content)}",
                  :og_image => "#{@picture.cover_photo_url(:cover)}"
             } %>
<% end %>

<!-- Latest Videos -->
<div id="latestVideos">
  <!-- Video 1 -->
  <h3><%= @picture.title %></h3>
  <div class="metaDetails">
    <p><%= @picture.views %> <%= t(:people_viewed_pic) %></p>
  </div>
  <div class="img-item img-popup">
    <%= image_tag @picture.cover_photo_url(:cover).to_s %>
    <figcaption class="img-title">
      <h5><%= t(:full_res) %></h5>    
    </figcaption>
  </div>

  <div class="btn-group btn-group-lg btn-group-justified">
    <a href="javascript:void(0)" onclick="PopupCenter('//www.facebook.com/sharer/sharer.php?u=<%= request.url %>', 'myPop1',600,450);" class="btn btn-facebook"><%= t(:share_fb) %></a>
    <a href="javascript:void(0)" onclick="PopupCenter('//twitter.com/intent/tweet?source=tweetbutton&original_referer=<%= request.url %>&text=<%= @picture.try(:title) %>&url=<%= request.url %>', 'myPop1',600,450);" class="btn btn-twitter"><%= t(:share_twitter) %></a>
  </div>

  <div class="metaDetails">
    <p class="small"><%= t(:published_on) %> <%= @picture.published_at.strftime("%d %B %Y") %> by <%= @picture.user.username.upcase %></p>
  </div>
<p class="text-justify"><%=h @picture.content %></p>

</div>
<!-- Latest Videos End -->

<!-- Random Videos -->
<div id="featuredVideos">
  <div class="separator m-b-xl">
    <span><%= t(:may_like) %></span>
  </div>

  <div class="row one-time">
    <% @random.each do |picture| %>
    <div class="col-md-3 col-sm-6 col-xs-6">
      <%= link_to view_path(picture) do %>
      <%= image_tag picture.cover_photo_url(:thumb).to_s, :class => 'img-responsive' %>
      <% end %>
      <h4><%= picture.title %></h4>
      <p class="small"><%= t(:published_on) %> <%= picture.published_at.strftime("%d %B %Y") %></p>
    </div>
    <% end %>
  </div>
</div>
<!-- Random Videos End -->


<script type="text/javascript">
  $(document).ready(function() {
    $('.img-popup').magnificPopup({
      items: {
        src: '<%= @picture.cover_photo_url %>'
      },
      type:'image'
    });
  });
</script>

<script type="text/javascript">
$(document).ready(function(){
  mixpanel.track("Picture viewed", {
      "Picture ID": '<%= @picture.pid %>'
  });
});
</script>