config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/register' => 'devise/registrations#new'
  end

  get 'pages/index'  

  scope "/:locale" do

    namespace :admin, path: '/master' do
      get "/" => "dashboards#index", as: 'master'
      resources :dashboards, only: [:index]
      resources :users do
        resources :videos, only: [:index, :edit, :update, :destroy]
        resources :pictures, only: [:index, :edit, :update, :destroy]
      end
    end

    resource :account, only: [:show, :edit, :update]
    resources :pictures do
      collection do
        get 'next_stories'
      end
    end
    resources :videos do
      collection do
        get 'next_stories'
      end
    end
    
  end

  get '/v=:id' => 'videos#show', as: 'watch' #example - awesomepv.dev/v=aNFo5HWC3QI
  get '/p=:id' => 'pictures#show', as: 'view'

  root 'pages#index'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Authenticable

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    { locale: I18n.locale }
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  def user_params
    params.require(:user).permit(:id, :username, :email,
      profile_attributes: [:id, :user_id, :full_name, :facebook_id])
  end

  def video_params
    params.require(:video).permit(:id, :user_id, :title, :description, :source, :youtube_id, :featured)
  end

  def picture_params
    params.require(:picture).permit(:id, :user_id, :title, :content, :cover_photo, :featured)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
  "#{controller_name} #{action_name}"
  end
end

app/views/application/_analytics.html.erb
<!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46146723-1', 'auto');
  ga('send', 'pageview');

</script>
<!-- Google Analytics End -->
<!-- Mixpanel Analytic Start -->
<script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2.2.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("6ee4a30b269d81d1b42c85725fbff03a");</script>
<!-- Mixpanel Analytic End -->

app/views/application/_footer.html.erb
<!-- Footer -->
<footer id="apvFooter">
  <div class="container">
    <div class="row">
      <div class="col-xs-4 col-md-5">
        <div class="pull-left">
          <ul class="list-inline nomar">
            <li class="m-r-md nopad"><a href=""><%= t(:contact) %></a></li>
            <li class="m-r-md nopad"><a href=""><%= t(:subscribe) %></a></li>
            <li class="m-r-md nopad"><%= link_to image_tag('en-flag.png'), root_path(locale: 'en') %></li>
            <li class="m-r-md nopad"><%= link_to image_tag('my-flag.png'), root_path(locale: 'my') %></li>
          </ul>
        </div>
      </div>
      <div class="col-xs-4 col-md-2">
        <div class="back-top" title="Top of Page">
          <span class="glyphicon glyphicon-arrow-up"></span> <%= t(:backTotop) %>
        </div>
      </div>
      <div class="col-xs-4 col-md-5">
        <div class="pull-right">
          <%= t(:copyright) %>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- Footer End -->

app/views/application/_header.html.erb
<!-- Branding Logo -->
<div class="row hidden-xs">
  <div class="col-xs-12">
    <div id="branding">
      <%= link_to "AwesomePV", root_path, :class => "apvLogo" %>
    </div>
  </div>
</div>
<!-- Branding Logo End -->

<!-- Navbar -->
<div id="apvNav">
  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainNav">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "AwesomePV", root_path, :class => "logo-xs visible-xs" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="mainNav">
      <ul class="nav navbar-nav nomar">
        <li class="active">
          <%= link_to root_path do %>
          <span class="glyphicon glyphicon-home"></span>
          <% end %>
        </li>
        <% if current_user.try(:admin) %>
        <li>
          <%= link_to admin_master_path do %>
          <span class="glyphicon glyphicon-lock"></span>
          <% end %>
        </li>
        <% end %>
        <li>
          <%= link_to t(:submit_video), new_video_path %>
        </li>
        <li>
          <%= link_to t(:submit_picture), new_picture_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right nomar">
        <% if user_signed_in? %>
        <li><%= link_to t(:my_profile), account_path %></li>
        <li>
          <%= link_to destroy_user_session_path, method: "delete" do %>
          <span class="glyphicon glyphicon-log-out"></span>
          <% end %>
        </li>
        <% else %>
        <li>
          <%= link_to login_path do %>
            <span class="glyphicon glyphicon-user"></span> <%= t(:login) %>
          <% end %>
        </li>
        <li>
          <%= link_to register_path do %>
            <span class="glyphicon glyphicon-lock"></span> <%= t(:register) %>
          <% end %>
        </li>
        <% end %>
      </ul>
      <!--
      <form class="navbar-form navbar-right hidden-xs" role="search">
        <div class="form-group">
          <span class="glyphicon glyphicon-search"></span>
          <input type="text" class="form-control">
        </div>
      </form>
      -->
    </div>
  </nav>
</div>
<!-- Navbar End -->

<script type="text/javascript">
$(document).ready(function() {
  var $header = $("#apvNav"),
      $clone = $header.before($header.clone().addClass("container clone"));
  
  $(window).on("scroll", function() {
      var fromTop = $(window).scrollTop();
      $("body").toggleClass("down", (fromTop > 200));
  });
});
</script>

app/views/application/_meta_tags.html.erb
<% og_description ||= "" %>
<% og_title ||= "" %>
<% og_type ||= "" %>
<% og_url ||= "" %>
<% og_image ||= "" %>

<% image_url ||= image_path('signature@2x.png') %>
<meta property="og:type" content="<%= !og_type.blank? ? og_type : 'website'%>" />
<meta property="og:title" content="<%= !og_title.blank? ? og_title : title %>"/>
<meta property="og:url" content="<%= !og_url.blank? ? og_url : request.url %>"/>
<meta property="og:image" content="<%= !og_image.blank? ? og_image : image_url('logo.png') %>"/>
<meta property="og:description" content="<%= !og_description.blank? ? og_description : description %>" />
<meta property="og:site_name" content="awesomepv.com"/>
<meta name="title" content="<%= title %>"/>
<meta name="description" content="<%= description %>" />
<link rel="canonical" href="<%= canonical %>" />

<%= favicon_link_tag 'favicon.ico', :rel => 'apple-touch-icon shortcut icon', :type => 'image/png' %>

app/views/application/_social.html.erb
<!-- Facebook -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=<%= Settings.fb_app_id %>&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- Facebook End -->

<!-- Twitter -->
<script type="text/javascript">
window.twttr=(function(d,s,id){var t,js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);return window.twttr||(t={_e:[],ready:function(f){t._e.push(f)}})}(document,"script","twitter-wjs"));
</script>
<!-- Twitter End -->
<!-- Google Search Start -->
<script>
  (function() {
    var cx = '001603565392639805733:yamilzyiya8';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<!-- Google Search End -->