config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/register' => 'devise/registrations#new'
  end

  get 'pages/index'  

  scope "/:locale" do

    namespace :admin, path: '/master' do
      get "/" => "dashboards#index", as: 'master'
      resources :dashboards, only: [:index]
      resources :users do
        resources :videos, only: [:index, :edit, :update, :destroy]
        resources :pictures, only: [:index, :edit, :update, :destroy]
      end
    end

    resource :account, only: [:show, :edit, :update]
    resources :pictures do
      collection do
        get 'next_stories'
      end
    end
    resources :videos do
      collection do
        get 'next_stories'
      end
    end
    
  end

  get '/v=:id' => 'videos#show', as: 'watch' #example - awesomepv.dev/v=aNFo5HWC3QI
  get '/p=:id' => 'pictures#show', as: 'view'

  root 'pages#index'
  
end

app/models/video.rb
class Video < ActiveRecord::Base
  acts_as_paranoid

  extend FriendlyId #https://github.com/norman/friendly_id

  friendly_id :vid, use: [:slugged, :finders, :history]

  belongs_to :user, foreign_key: :user_id

  validates :title, length: { maximum: 240 }, presence: true
  validates :description, length: { maximum: 500 }, allow_blank: true
  validates :youtube_id, presence: true, uniqueness: true

  self.per_page = 12

  default_scope -> { order('videos.created_at DESC') }
  scope :published, -> { where('state = ?', 'published').unscope(:order).order('`videos`.published_at DESC') }
  scope :featured, -> { where(featured: true) }
  scope :published_only, -> { where('featured IS NOT TRUE') }
  scope :random, -> { unscope(:order).order('RAND()') }

  after_create :send_video_email

  protected

  def published?
    state == 'published'
  end

  def send_video_email
    VideoMailer.video_email(self.user).deliver
 end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  before_filter :set_user, only: [:index, :edit, :update, :destroy]
  before_filter :set_video, only: [:edit, :update, :destroy]
  before_filter :store_location, only: [:index]
  before_filter :require_admin

  def index
    @videos = Video.where(user_id: @user)
    respond_to do |format|
      format.html { @videos }
      format.json { render json: @videos.to_json }
    end
  end

  def edit
    if @video
      render
    else
      redirect_to admin_user_videos_path, notice: "Video not found."
    end
  end

  def update
    if @video.update(video_params)
      redirect_to admin_user_videos_path, notice: "Video #{@video.vid} has been updated."
    else
      render 'edit'
    end
  end

  def destroy
    @video.destroy
    redirect_to admin_user_videos_path, notice: "Video has been deleted."
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_video
    @video = Video.where(slug: params[:id], user: @user).take
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :set_user, only: [:index, :new, :create, :edit, :update, :destroy]
  before_filter :set_video, only: [:edit, :update, :destroy]
  before_filter :require_user, only: [:index, :new, :create, :edit, :update, :destroy]
  before_filter :store_location, only: [:index]

  def index
    @videos = Video.where(user_id: @user)
    respond_to do |format|
      format.html { @videos }
      format.json { render json: @videos.to_json }
    end
  end

  def new
    @video ||= Video.new
    render
  end

  def create
    @video = @user.videos.new(video_params)
    if @video.save
      @video.update_attributes(:state => "published")
      @video.update_attributes(:published_at => Time.zone.now)

      random = [('a'..'z'), ('A'..'Z'), ('1'..'9')].map { |i| i.to_a }.flatten
      vid = (0...12).map { random[rand(random.length)] }.join
      @video.update_attributes(:vid => vid)

      redirect_to watch_path(@video), notice: "New video has been created."
    else
      render 'new'
    end
  end

  def show
    @video = Video.find(params[:id])
    respond_to do |format|
      format.html { @video }
      format.json { render json: @video.to_json }
    end

    @videos = Video.all.limit(4)
    @random = @videos.random
    @video.increment!(:views)
  end

  def edit
    if @video
      render
    else
      redirect_to video_path, notice: "Video not found."
    end
  end

  def update
    if @video.update(video_params)
      redirect_to video_path, notice: "#{@video.title} has been updated."
    else
      render 'edit'
    end
  end

  def destroy
    @video.destroy
    redirect_to videos_path, notice: "Video has been deleted."
  end

  private

  def set_user
    @user = current_user
  end

  def set_video
    @video = Video.where(slug: params[:id], user: @user).take
  end
end

app/helpers/admin/videos_helper.rb
module Admin::VideosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/videos/_sidebar.html.erb
<div class="list-group">
  <%= link_to admin_user_path(@user.username), :class => 'list-group-item' do %>
    <h5>User Details</h5>
    <p class="list-group-item-text">Manage user account details</p>
  <% end %>
  <%= link_to admin_user_videos_path(@user.username), :class => 'list-group-item active' do %>
    <h5>Video Details</h5>
    <p class="list-group-item-text">Manage submitted video</p>
  <% end %>
  <%= link_to admin_user_pictures_path(@user.username), :class => 'list-group-item' do %>
    <h5>Picture Details</h5>
    <p class="list-group-item-text">Manage submitted picture</p>
  <% end %>
</div>

app/views/admin/videos/edit.html.erb
<div class="page-header">
  <h1>New Video <small>Create your new video here.</small></h1>
</div>

<div class="row">
  <div class="col-md-4">
    <%= render partial: "sidebar" %>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Video Details</h3>
      </div>
      <%= form_for :video, url: admin_user_video_path, method: :patch do |f| %>
      <div class="panel-body">

        <% if @video.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><%= pluralize(@video.errors.count, "error") %> prohibited
            this video from being saved:</strong>
            <ul>
              <% @video.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
        <% end %>
        
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :title, "Video Title" %>
              <%= f.text_field :title, :class => "form-control" %>
              <p class="small help-block">Not more than 240 characters.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :description, "Video Description" %>
              <%= f.text_area :description, :class => "form-control", :rows => 4 %>
              <p class="small help-block">Not more than 500 characters.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :youtube_id, "Youtube ID" %>
              <%= f.text_field :youtube_id, :class => "form-control" %>
              <p class="small help-block">Make sure you just copy the Youtube ID (details).</p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :source, "Source From" %>
              <%= f.select(:source, options_for_select([['Youtube', 'Youtube'], ['Vimeo', 'Vimeo']], @video.source), {}, {:class => "form-control"}) %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="checkbox">
              <label>
              <%= f.check_box :featured, :type => 'checkbox' %> Tick to mark this video as featured
              </label>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <div class="form-group">
          <%= f.button "Update video", :class => "btn btn-primary", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Updating ..." } %>
          <%= link_to 'Cancel', videos_path, :class => "btn btn-link" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/videos/index.html.erb
<div class="page-header">
  <h1>Video List <small>Manage your video details here.</small></h1>
</div>

<div class="row">
  <div class="col-md-4">
    <%= render partial: "sidebar" %>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">List Submitted Video</h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover" id="videoDetails">
            <thead>
              <tr>
                <th>Video Title</th>
                <th>Date Added</th>
                <th class="col-md-2">Action</th>
              </tr>
            </thead>
            <tbody>
              <% @videos.each do |video| %>
              <tr>
                <td><%= video.try(:title) %></td>
                <td><%= video.try(:created_at).strftime("%d %B %Y") %></td>
                <td>
                  <div class="btn-group btn-group-xs btn-group-justified">
                  <%= link_to watch_path(video), :class => "btn btn-default", "data-toggle" => "tooltip", :title => "Show the video" do %>
                    <span class="glyphicon glyphicon-eye-open"></span>
                  <% end %>
                  <%= link_to edit_admin_user_video_path(id:video), :class => "btn btn-info", "data-toggle" => "tooltip", :title => "Edit this video" do %>
                    <span class="glyphicon glyphicon-edit"></span>
                  <% end %>
                  <%= link_to admin_user_video_path(id:video), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", "data-toggle" => "tooltip", :title => "Remove this video" do %>
                    <span class="glyphicon glyphicon-remove"></span>
                  <% end %>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready( function () {
    $('#videoDetails').DataTable();
} );
</script>